/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UmcBreadcrumbs {}
  interface UmcButton {}
  interface UmcCodeExample {}
  interface UmcColorSwatch {
    'name': string;
  }
  interface UmcColumn {
    'alignment': string;
    'colspan': string;
    'width': string;
  }
  interface UmcColumnSection {}
  interface UmcContentBlock {}
  interface UmcContentHeader {}
  interface UmcContentSection {}
  interface UmcContentSectionWrapper {}
  interface UmcDevStatusbar {}
  interface UmcDivider {}
  interface UmcGridBlock {}
  interface UmcGridRow {}
  interface UmcHeader {}
  interface UmcHeaderSection {}
  interface UmcHeading {}
  interface UmcHeroImage {}
  interface UmcHeroSection {}
  interface UmcIcon {}
  interface UmcLabel {}
  interface UmcLinkList {
    'orientation': string;
    'title': string;
  }
  interface UmcLinkListItem {
    'active': boolean;
    'href': string;
    'icon': string;
    'label': string;
  }
  interface UmcList {}
  interface UmcListHeader {}
  interface UmcListItem {}
  interface UmcListItemHeader {}
  interface UmcListingBlock {}
  interface UmcLogo {
    'src': string;
  }
  interface UmcMenuSection {}
  interface UmcMenuToggle {}
  interface UmcPublicationsList {}
  interface UmcPublicationsListItem {}
  interface UmcPublicationsListItemAuthors {}
  interface UmcPublicationsListItemPublication {}
  interface UmcPublicationsListItemTitle {}
  interface UmcResearcher {}
  interface UmcResearcherImage {}
  interface UmcResearchers {}
  interface UmcResearchersList {}
  interface UmcRichTextBlock {}
  interface UmcSearchInput {}
  interface UmcSection {}
  interface UmcSectionContainer {}
  interface UmcSidebar {}
  interface UmcStyleSection {
    'title': string;
  }
  interface UmcTab {
    'active': boolean;
    'label': string;
  }
  interface UmcTabs {}
  interface UmcTag {
    'label': string;
  }
  interface UmcTag {}
  interface UmcTagList {}
  interface UmcTeaser {}
  interface UmcTeaserBody {}
  interface UmcTeaserHeader {}
  interface UmcTeaserImage {}
  interface UmcTeaserLink {}
  interface UmcTeaserSection {}
  interface UmcTeaserText {}
  interface UmcTheme {}
  interface UmcTitleBlock {}
}

declare global {


  interface HTMLUmcBreadcrumbsElement extends Components.UmcBreadcrumbs, HTMLStencilElement {}
  var HTMLUmcBreadcrumbsElement: {
    prototype: HTMLUmcBreadcrumbsElement;
    new (): HTMLUmcBreadcrumbsElement;
  };

  interface HTMLUmcButtonElement extends Components.UmcButton, HTMLStencilElement {}
  var HTMLUmcButtonElement: {
    prototype: HTMLUmcButtonElement;
    new (): HTMLUmcButtonElement;
  };

  interface HTMLUmcCodeExampleElement extends Components.UmcCodeExample, HTMLStencilElement {}
  var HTMLUmcCodeExampleElement: {
    prototype: HTMLUmcCodeExampleElement;
    new (): HTMLUmcCodeExampleElement;
  };

  interface HTMLUmcColorSwatchElement extends Components.UmcColorSwatch, HTMLStencilElement {}
  var HTMLUmcColorSwatchElement: {
    prototype: HTMLUmcColorSwatchElement;
    new (): HTMLUmcColorSwatchElement;
  };

  interface HTMLUmcColumnElement extends Components.UmcColumn, HTMLStencilElement {}
  var HTMLUmcColumnElement: {
    prototype: HTMLUmcColumnElement;
    new (): HTMLUmcColumnElement;
  };

  interface HTMLUmcColumnSectionElement extends Components.UmcColumnSection, HTMLStencilElement {}
  var HTMLUmcColumnSectionElement: {
    prototype: HTMLUmcColumnSectionElement;
    new (): HTMLUmcColumnSectionElement;
  };

  interface HTMLUmcContentBlockElement extends Components.UmcContentBlock, HTMLStencilElement {}
  var HTMLUmcContentBlockElement: {
    prototype: HTMLUmcContentBlockElement;
    new (): HTMLUmcContentBlockElement;
  };

  interface HTMLUmcContentHeaderElement extends Components.UmcContentHeader, HTMLStencilElement {}
  var HTMLUmcContentHeaderElement: {
    prototype: HTMLUmcContentHeaderElement;
    new (): HTMLUmcContentHeaderElement;
  };

  interface HTMLUmcContentSectionElement extends Components.UmcContentSection, HTMLStencilElement {}
  var HTMLUmcContentSectionElement: {
    prototype: HTMLUmcContentSectionElement;
    new (): HTMLUmcContentSectionElement;
  };

  interface HTMLUmcContentSectionWrapperElement extends Components.UmcContentSectionWrapper, HTMLStencilElement {}
  var HTMLUmcContentSectionWrapperElement: {
    prototype: HTMLUmcContentSectionWrapperElement;
    new (): HTMLUmcContentSectionWrapperElement;
  };

  interface HTMLUmcDevStatusbarElement extends Components.UmcDevStatusbar, HTMLStencilElement {}
  var HTMLUmcDevStatusbarElement: {
    prototype: HTMLUmcDevStatusbarElement;
    new (): HTMLUmcDevStatusbarElement;
  };

  interface HTMLUmcDividerElement extends Components.UmcDivider, HTMLStencilElement {}
  var HTMLUmcDividerElement: {
    prototype: HTMLUmcDividerElement;
    new (): HTMLUmcDividerElement;
  };

  interface HTMLUmcGridBlockElement extends Components.UmcGridBlock, HTMLStencilElement {}
  var HTMLUmcGridBlockElement: {
    prototype: HTMLUmcGridBlockElement;
    new (): HTMLUmcGridBlockElement;
  };

  interface HTMLUmcGridRowElement extends Components.UmcGridRow, HTMLStencilElement {}
  var HTMLUmcGridRowElement: {
    prototype: HTMLUmcGridRowElement;
    new (): HTMLUmcGridRowElement;
  };

  interface HTMLUmcHeaderElement extends Components.UmcHeader, HTMLStencilElement {}
  var HTMLUmcHeaderElement: {
    prototype: HTMLUmcHeaderElement;
    new (): HTMLUmcHeaderElement;
  };

  interface HTMLUmcHeaderSectionElement extends Components.UmcHeaderSection, HTMLStencilElement {}
  var HTMLUmcHeaderSectionElement: {
    prototype: HTMLUmcHeaderSectionElement;
    new (): HTMLUmcHeaderSectionElement;
  };

  interface HTMLUmcHeadingElement extends Components.UmcHeading, HTMLStencilElement {}
  var HTMLUmcHeadingElement: {
    prototype: HTMLUmcHeadingElement;
    new (): HTMLUmcHeadingElement;
  };

  interface HTMLUmcHeroImageElement extends Components.UmcHeroImage, HTMLStencilElement {}
  var HTMLUmcHeroImageElement: {
    prototype: HTMLUmcHeroImageElement;
    new (): HTMLUmcHeroImageElement;
  };

  interface HTMLUmcHeroSectionElement extends Components.UmcHeroSection, HTMLStencilElement {}
  var HTMLUmcHeroSectionElement: {
    prototype: HTMLUmcHeroSectionElement;
    new (): HTMLUmcHeroSectionElement;
  };

  interface HTMLUmcIconElement extends Components.UmcIcon, HTMLStencilElement {}
  var HTMLUmcIconElement: {
    prototype: HTMLUmcIconElement;
    new (): HTMLUmcIconElement;
  };

  interface HTMLUmcLabelElement extends Components.UmcLabel, HTMLStencilElement {}
  var HTMLUmcLabelElement: {
    prototype: HTMLUmcLabelElement;
    new (): HTMLUmcLabelElement;
  };

  interface HTMLUmcLinkListElement extends Components.UmcLinkList, HTMLStencilElement {}
  var HTMLUmcLinkListElement: {
    prototype: HTMLUmcLinkListElement;
    new (): HTMLUmcLinkListElement;
  };

  interface HTMLUmcLinkListItemElement extends Components.UmcLinkListItem, HTMLStencilElement {}
  var HTMLUmcLinkListItemElement: {
    prototype: HTMLUmcLinkListItemElement;
    new (): HTMLUmcLinkListItemElement;
  };

  interface HTMLUmcListElement extends Components.UmcList, HTMLStencilElement {}
  var HTMLUmcListElement: {
    prototype: HTMLUmcListElement;
    new (): HTMLUmcListElement;
  };

  interface HTMLUmcListHeaderElement extends Components.UmcListHeader, HTMLStencilElement {}
  var HTMLUmcListHeaderElement: {
    prototype: HTMLUmcListHeaderElement;
    new (): HTMLUmcListHeaderElement;
  };

  interface HTMLUmcListItemElement extends Components.UmcListItem, HTMLStencilElement {}
  var HTMLUmcListItemElement: {
    prototype: HTMLUmcListItemElement;
    new (): HTMLUmcListItemElement;
  };

  interface HTMLUmcListItemHeaderElement extends Components.UmcListItemHeader, HTMLStencilElement {}
  var HTMLUmcListItemHeaderElement: {
    prototype: HTMLUmcListItemHeaderElement;
    new (): HTMLUmcListItemHeaderElement;
  };

  interface HTMLUmcListingBlockElement extends Components.UmcListingBlock, HTMLStencilElement {}
  var HTMLUmcListingBlockElement: {
    prototype: HTMLUmcListingBlockElement;
    new (): HTMLUmcListingBlockElement;
  };

  interface HTMLUmcLogoElement extends Components.UmcLogo, HTMLStencilElement {}
  var HTMLUmcLogoElement: {
    prototype: HTMLUmcLogoElement;
    new (): HTMLUmcLogoElement;
  };

  interface HTMLUmcMenuSectionElement extends Components.UmcMenuSection, HTMLStencilElement {}
  var HTMLUmcMenuSectionElement: {
    prototype: HTMLUmcMenuSectionElement;
    new (): HTMLUmcMenuSectionElement;
  };

  interface HTMLUmcMenuToggleElement extends Components.UmcMenuToggle, HTMLStencilElement {}
  var HTMLUmcMenuToggleElement: {
    prototype: HTMLUmcMenuToggleElement;
    new (): HTMLUmcMenuToggleElement;
  };

  interface HTMLUmcPublicationsListElement extends Components.UmcPublicationsList, HTMLStencilElement {}
  var HTMLUmcPublicationsListElement: {
    prototype: HTMLUmcPublicationsListElement;
    new (): HTMLUmcPublicationsListElement;
  };

  interface HTMLUmcPublicationsListItemElement extends Components.UmcPublicationsListItem, HTMLStencilElement {}
  var HTMLUmcPublicationsListItemElement: {
    prototype: HTMLUmcPublicationsListItemElement;
    new (): HTMLUmcPublicationsListItemElement;
  };

  interface HTMLUmcPublicationsListItemAuthorsElement extends Components.UmcPublicationsListItemAuthors, HTMLStencilElement {}
  var HTMLUmcPublicationsListItemAuthorsElement: {
    prototype: HTMLUmcPublicationsListItemAuthorsElement;
    new (): HTMLUmcPublicationsListItemAuthorsElement;
  };

  interface HTMLUmcPublicationsListItemPublicationElement extends Components.UmcPublicationsListItemPublication, HTMLStencilElement {}
  var HTMLUmcPublicationsListItemPublicationElement: {
    prototype: HTMLUmcPublicationsListItemPublicationElement;
    new (): HTMLUmcPublicationsListItemPublicationElement;
  };

  interface HTMLUmcPublicationsListItemTitleElement extends Components.UmcPublicationsListItemTitle, HTMLStencilElement {}
  var HTMLUmcPublicationsListItemTitleElement: {
    prototype: HTMLUmcPublicationsListItemTitleElement;
    new (): HTMLUmcPublicationsListItemTitleElement;
  };

  interface HTMLUmcResearcherElement extends Components.UmcResearcher, HTMLStencilElement {}
  var HTMLUmcResearcherElement: {
    prototype: HTMLUmcResearcherElement;
    new (): HTMLUmcResearcherElement;
  };

  interface HTMLUmcResearcherImageElement extends Components.UmcResearcherImage, HTMLStencilElement {}
  var HTMLUmcResearcherImageElement: {
    prototype: HTMLUmcResearcherImageElement;
    new (): HTMLUmcResearcherImageElement;
  };

  interface HTMLUmcResearchersElement extends Components.UmcResearchers, HTMLStencilElement {}
  var HTMLUmcResearchersElement: {
    prototype: HTMLUmcResearchersElement;
    new (): HTMLUmcResearchersElement;
  };

  interface HTMLUmcResearchersListElement extends Components.UmcResearchersList, HTMLStencilElement {}
  var HTMLUmcResearchersListElement: {
    prototype: HTMLUmcResearchersListElement;
    new (): HTMLUmcResearchersListElement;
  };

  interface HTMLUmcRichTextBlockElement extends Components.UmcRichTextBlock, HTMLStencilElement {}
  var HTMLUmcRichTextBlockElement: {
    prototype: HTMLUmcRichTextBlockElement;
    new (): HTMLUmcRichTextBlockElement;
  };

  interface HTMLUmcSearchInputElement extends Components.UmcSearchInput, HTMLStencilElement {}
  var HTMLUmcSearchInputElement: {
    prototype: HTMLUmcSearchInputElement;
    new (): HTMLUmcSearchInputElement;
  };

  interface HTMLUmcSectionElement extends Components.UmcSection, HTMLStencilElement {}
  var HTMLUmcSectionElement: {
    prototype: HTMLUmcSectionElement;
    new (): HTMLUmcSectionElement;
  };

  interface HTMLUmcSectionContainerElement extends Components.UmcSectionContainer, HTMLStencilElement {}
  var HTMLUmcSectionContainerElement: {
    prototype: HTMLUmcSectionContainerElement;
    new (): HTMLUmcSectionContainerElement;
  };

  interface HTMLUmcSidebarElement extends Components.UmcSidebar, HTMLStencilElement {}
  var HTMLUmcSidebarElement: {
    prototype: HTMLUmcSidebarElement;
    new (): HTMLUmcSidebarElement;
  };

  interface HTMLUmcStyleSectionElement extends Components.UmcStyleSection, HTMLStencilElement {}
  var HTMLUmcStyleSectionElement: {
    prototype: HTMLUmcStyleSectionElement;
    new (): HTMLUmcStyleSectionElement;
  };

  interface HTMLUmcTabElement extends Components.UmcTab, HTMLStencilElement {}
  var HTMLUmcTabElement: {
    prototype: HTMLUmcTabElement;
    new (): HTMLUmcTabElement;
  };

  interface HTMLUmcTabsElement extends Components.UmcTabs, HTMLStencilElement {}
  var HTMLUmcTabsElement: {
    prototype: HTMLUmcTabsElement;
    new (): HTMLUmcTabsElement;
  };

  interface HTMLUmcTagElement extends Components.UmcTag, HTMLStencilElement {}
  var HTMLUmcTagElement: {
    prototype: HTMLUmcTagElement;
    new (): HTMLUmcTagElement;
  };

  interface HTMLUmcTagElement extends Components.UmcTag, HTMLStencilElement {}
  var HTMLUmcTagElement: {
    prototype: HTMLUmcTagElement;
    new (): HTMLUmcTagElement;
  };

  interface HTMLUmcTagListElement extends Components.UmcTagList, HTMLStencilElement {}
  var HTMLUmcTagListElement: {
    prototype: HTMLUmcTagListElement;
    new (): HTMLUmcTagListElement;
  };

  interface HTMLUmcTeaserElement extends Components.UmcTeaser, HTMLStencilElement {}
  var HTMLUmcTeaserElement: {
    prototype: HTMLUmcTeaserElement;
    new (): HTMLUmcTeaserElement;
  };

  interface HTMLUmcTeaserBodyElement extends Components.UmcTeaserBody, HTMLStencilElement {}
  var HTMLUmcTeaserBodyElement: {
    prototype: HTMLUmcTeaserBodyElement;
    new (): HTMLUmcTeaserBodyElement;
  };

  interface HTMLUmcTeaserHeaderElement extends Components.UmcTeaserHeader, HTMLStencilElement {}
  var HTMLUmcTeaserHeaderElement: {
    prototype: HTMLUmcTeaserHeaderElement;
    new (): HTMLUmcTeaserHeaderElement;
  };

  interface HTMLUmcTeaserImageElement extends Components.UmcTeaserImage, HTMLStencilElement {}
  var HTMLUmcTeaserImageElement: {
    prototype: HTMLUmcTeaserImageElement;
    new (): HTMLUmcTeaserImageElement;
  };

  interface HTMLUmcTeaserLinkElement extends Components.UmcTeaserLink, HTMLStencilElement {}
  var HTMLUmcTeaserLinkElement: {
    prototype: HTMLUmcTeaserLinkElement;
    new (): HTMLUmcTeaserLinkElement;
  };

  interface HTMLUmcTeaserSectionElement extends Components.UmcTeaserSection, HTMLStencilElement {}
  var HTMLUmcTeaserSectionElement: {
    prototype: HTMLUmcTeaserSectionElement;
    new (): HTMLUmcTeaserSectionElement;
  };

  interface HTMLUmcTeaserTextElement extends Components.UmcTeaserText, HTMLStencilElement {}
  var HTMLUmcTeaserTextElement: {
    prototype: HTMLUmcTeaserTextElement;
    new (): HTMLUmcTeaserTextElement;
  };

  interface HTMLUmcThemeElement extends Components.UmcTheme, HTMLStencilElement {}
  var HTMLUmcThemeElement: {
    prototype: HTMLUmcThemeElement;
    new (): HTMLUmcThemeElement;
  };

  interface HTMLUmcTitleBlockElement extends Components.UmcTitleBlock, HTMLStencilElement {}
  var HTMLUmcTitleBlockElement: {
    prototype: HTMLUmcTitleBlockElement;
    new (): HTMLUmcTitleBlockElement;
  };
  interface HTMLElementTagNameMap {
    'umc-breadcrumbs': HTMLUmcBreadcrumbsElement;
    'umc-button': HTMLUmcButtonElement;
    'umc-code-example': HTMLUmcCodeExampleElement;
    'umc-color-swatch': HTMLUmcColorSwatchElement;
    'umc-column': HTMLUmcColumnElement;
    'umc-column-section': HTMLUmcColumnSectionElement;
    'umc-content-block': HTMLUmcContentBlockElement;
    'umc-content-header': HTMLUmcContentHeaderElement;
    'umc-content-section': HTMLUmcContentSectionElement;
    'umc-content-section-wrapper': HTMLUmcContentSectionWrapperElement;
    'umc-dev-statusbar': HTMLUmcDevStatusbarElement;
    'umc-divider': HTMLUmcDividerElement;
    'umc-grid-block': HTMLUmcGridBlockElement;
    'umc-grid-row': HTMLUmcGridRowElement;
    'umc-header': HTMLUmcHeaderElement;
    'umc-header-section': HTMLUmcHeaderSectionElement;
    'umc-heading': HTMLUmcHeadingElement;
    'umc-hero-image': HTMLUmcHeroImageElement;
    'umc-hero-section': HTMLUmcHeroSectionElement;
    'umc-icon': HTMLUmcIconElement;
    'umc-label': HTMLUmcLabelElement;
    'umc-link-list': HTMLUmcLinkListElement;
    'umc-link-list-item': HTMLUmcLinkListItemElement;
    'umc-list': HTMLUmcListElement;
    'umc-list-header': HTMLUmcListHeaderElement;
    'umc-list-item': HTMLUmcListItemElement;
    'umc-list-item-header': HTMLUmcListItemHeaderElement;
    'umc-listing-block': HTMLUmcListingBlockElement;
    'umc-logo': HTMLUmcLogoElement;
    'umc-menu-section': HTMLUmcMenuSectionElement;
    'umc-menu-toggle': HTMLUmcMenuToggleElement;
    'umc-publications-list': HTMLUmcPublicationsListElement;
    'umc-publications-list-item': HTMLUmcPublicationsListItemElement;
    'umc-publications-list-item-authors': HTMLUmcPublicationsListItemAuthorsElement;
    'umc-publications-list-item-publication': HTMLUmcPublicationsListItemPublicationElement;
    'umc-publications-list-item-title': HTMLUmcPublicationsListItemTitleElement;
    'umc-researcher': HTMLUmcResearcherElement;
    'umc-researcher-image': HTMLUmcResearcherImageElement;
    'umc-researchers': HTMLUmcResearchersElement;
    'umc-researchers-list': HTMLUmcResearchersListElement;
    'umc-rich-text-block': HTMLUmcRichTextBlockElement;
    'umc-search-input': HTMLUmcSearchInputElement;
    'umc-section': HTMLUmcSectionElement;
    'umc-section-container': HTMLUmcSectionContainerElement;
    'umc-sidebar': HTMLUmcSidebarElement;
    'umc-style-section': HTMLUmcStyleSectionElement;
    'umc-tab': HTMLUmcTabElement;
    'umc-tabs': HTMLUmcTabsElement;
    'umc-tag': HTMLUmcTagElement;
    'umc-tag': HTMLUmcTagElement;
    'umc-tag-list': HTMLUmcTagListElement;
    'umc-teaser': HTMLUmcTeaserElement;
    'umc-teaser-body': HTMLUmcTeaserBodyElement;
    'umc-teaser-header': HTMLUmcTeaserHeaderElement;
    'umc-teaser-image': HTMLUmcTeaserImageElement;
    'umc-teaser-link': HTMLUmcTeaserLinkElement;
    'umc-teaser-section': HTMLUmcTeaserSectionElement;
    'umc-teaser-text': HTMLUmcTeaserTextElement;
    'umc-theme': HTMLUmcThemeElement;
    'umc-title-block': HTMLUmcTitleBlockElement;
  }
}

declare namespace LocalJSX {
  interface UmcBreadcrumbs {}
  interface UmcButton {}
  interface UmcCodeExample {}
  interface UmcColorSwatch {
    'name'?: string;
  }
  interface UmcColumn {
    'alignment'?: string;
    'colspan'?: string;
    'width'?: string;
  }
  interface UmcColumnSection {}
  interface UmcContentBlock {}
  interface UmcContentHeader {}
  interface UmcContentSection {}
  interface UmcContentSectionWrapper {}
  interface UmcDevStatusbar {}
  interface UmcDivider {}
  interface UmcGridBlock {}
  interface UmcGridRow {}
  interface UmcHeader {}
  interface UmcHeaderSection {}
  interface UmcHeading {}
  interface UmcHeroImage {}
  interface UmcHeroSection {}
  interface UmcIcon {}
  interface UmcLabel {}
  interface UmcLinkList {
    'orientation'?: string;
    'title'?: string;
  }
  interface UmcLinkListItem {
    'active'?: boolean;
    'href'?: string;
    'icon'?: string;
    'label'?: string;
  }
  interface UmcList {}
  interface UmcListHeader {}
  interface UmcListItem {}
  interface UmcListItemHeader {}
  interface UmcListingBlock {}
  interface UmcLogo {
    'src'?: string;
  }
  interface UmcMenuSection {
    'onOnToggle'?: (event: CustomEvent<any>) => void;
  }
  interface UmcMenuToggle {
    'onOnToggle'?: (event: CustomEvent<any>) => void;
  }
  interface UmcPublicationsList {}
  interface UmcPublicationsListItem {}
  interface UmcPublicationsListItemAuthors {}
  interface UmcPublicationsListItemPublication {}
  interface UmcPublicationsListItemTitle {}
  interface UmcResearcher {}
  interface UmcResearcherImage {}
  interface UmcResearchers {}
  interface UmcResearchersList {}
  interface UmcRichTextBlock {}
  interface UmcSearchInput {}
  interface UmcSection {
    'onOnToggle'?: (event: CustomEvent<any>) => void;
  }
  interface UmcSectionContainer {}
  interface UmcSidebar {}
  interface UmcStyleSection {
    'onOnToggle'?: (event: CustomEvent<any>) => void;
    'title'?: string;
  }
  interface UmcTab {
    'active'?: boolean;
    'label'?: string;
  }
  interface UmcTabs {}
  interface UmcTag {
    'label'?: string;
  }
  interface UmcTag {}
  interface UmcTagList {}
  interface UmcTeaser {}
  interface UmcTeaserBody {}
  interface UmcTeaserHeader {}
  interface UmcTeaserImage {}
  interface UmcTeaserLink {}
  interface UmcTeaserSection {}
  interface UmcTeaserText {}
  interface UmcTheme {}
  interface UmcTitleBlock {}

  interface IntrinsicElements {
    'umc-breadcrumbs': UmcBreadcrumbs;
    'umc-button': UmcButton;
    'umc-code-example': UmcCodeExample;
    'umc-color-swatch': UmcColorSwatch;
    'umc-column': UmcColumn;
    'umc-column-section': UmcColumnSection;
    'umc-content-block': UmcContentBlock;
    'umc-content-header': UmcContentHeader;
    'umc-content-section': UmcContentSection;
    'umc-content-section-wrapper': UmcContentSectionWrapper;
    'umc-dev-statusbar': UmcDevStatusbar;
    'umc-divider': UmcDivider;
    'umc-grid-block': UmcGridBlock;
    'umc-grid-row': UmcGridRow;
    'umc-header': UmcHeader;
    'umc-header-section': UmcHeaderSection;
    'umc-heading': UmcHeading;
    'umc-hero-image': UmcHeroImage;
    'umc-hero-section': UmcHeroSection;
    'umc-icon': UmcIcon;
    'umc-label': UmcLabel;
    'umc-link-list': UmcLinkList;
    'umc-link-list-item': UmcLinkListItem;
    'umc-list': UmcList;
    'umc-list-header': UmcListHeader;
    'umc-list-item': UmcListItem;
    'umc-list-item-header': UmcListItemHeader;
    'umc-listing-block': UmcListingBlock;
    'umc-logo': UmcLogo;
    'umc-menu-section': UmcMenuSection;
    'umc-menu-toggle': UmcMenuToggle;
    'umc-publications-list': UmcPublicationsList;
    'umc-publications-list-item': UmcPublicationsListItem;
    'umc-publications-list-item-authors': UmcPublicationsListItemAuthors;
    'umc-publications-list-item-publication': UmcPublicationsListItemPublication;
    'umc-publications-list-item-title': UmcPublicationsListItemTitle;
    'umc-researcher': UmcResearcher;
    'umc-researcher-image': UmcResearcherImage;
    'umc-researchers': UmcResearchers;
    'umc-researchers-list': UmcResearchersList;
    'umc-rich-text-block': UmcRichTextBlock;
    'umc-search-input': UmcSearchInput;
    'umc-section': UmcSection;
    'umc-section-container': UmcSectionContainer;
    'umc-sidebar': UmcSidebar;
    'umc-style-section': UmcStyleSection;
    'umc-tab': UmcTab;
    'umc-tabs': UmcTabs;
    'umc-tag': UmcTag;
    'umc-tag': UmcTag;
    'umc-tag-list': UmcTagList;
    'umc-teaser': UmcTeaser;
    'umc-teaser-body': UmcTeaserBody;
    'umc-teaser-header': UmcTeaserHeader;
    'umc-teaser-image': UmcTeaserImage;
    'umc-teaser-link': UmcTeaserLink;
    'umc-teaser-section': UmcTeaserSection;
    'umc-teaser-text': UmcTeaserText;
    'umc-theme': UmcTheme;
    'umc-title-block': UmcTitleBlock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'umc-breadcrumbs': LocalJSX.UmcBreadcrumbs & JSXBase.HTMLAttributes<HTMLUmcBreadcrumbsElement>;
      'umc-button': LocalJSX.UmcButton & JSXBase.HTMLAttributes<HTMLUmcButtonElement>;
      'umc-code-example': LocalJSX.UmcCodeExample & JSXBase.HTMLAttributes<HTMLUmcCodeExampleElement>;
      'umc-color-swatch': LocalJSX.UmcColorSwatch & JSXBase.HTMLAttributes<HTMLUmcColorSwatchElement>;
      'umc-column': LocalJSX.UmcColumn & JSXBase.HTMLAttributes<HTMLUmcColumnElement>;
      'umc-column-section': LocalJSX.UmcColumnSection & JSXBase.HTMLAttributes<HTMLUmcColumnSectionElement>;
      'umc-content-block': LocalJSX.UmcContentBlock & JSXBase.HTMLAttributes<HTMLUmcContentBlockElement>;
      'umc-content-header': LocalJSX.UmcContentHeader & JSXBase.HTMLAttributes<HTMLUmcContentHeaderElement>;
      'umc-content-section': LocalJSX.UmcContentSection & JSXBase.HTMLAttributes<HTMLUmcContentSectionElement>;
      'umc-content-section-wrapper': LocalJSX.UmcContentSectionWrapper & JSXBase.HTMLAttributes<HTMLUmcContentSectionWrapperElement>;
      'umc-dev-statusbar': LocalJSX.UmcDevStatusbar & JSXBase.HTMLAttributes<HTMLUmcDevStatusbarElement>;
      'umc-divider': LocalJSX.UmcDivider & JSXBase.HTMLAttributes<HTMLUmcDividerElement>;
      'umc-grid-block': LocalJSX.UmcGridBlock & JSXBase.HTMLAttributes<HTMLUmcGridBlockElement>;
      'umc-grid-row': LocalJSX.UmcGridRow & JSXBase.HTMLAttributes<HTMLUmcGridRowElement>;
      'umc-header': LocalJSX.UmcHeader & JSXBase.HTMLAttributes<HTMLUmcHeaderElement>;
      'umc-header-section': LocalJSX.UmcHeaderSection & JSXBase.HTMLAttributes<HTMLUmcHeaderSectionElement>;
      'umc-heading': LocalJSX.UmcHeading & JSXBase.HTMLAttributes<HTMLUmcHeadingElement>;
      'umc-hero-image': LocalJSX.UmcHeroImage & JSXBase.HTMLAttributes<HTMLUmcHeroImageElement>;
      'umc-hero-section': LocalJSX.UmcHeroSection & JSXBase.HTMLAttributes<HTMLUmcHeroSectionElement>;
      'umc-icon': LocalJSX.UmcIcon & JSXBase.HTMLAttributes<HTMLUmcIconElement>;
      'umc-label': LocalJSX.UmcLabel & JSXBase.HTMLAttributes<HTMLUmcLabelElement>;
      'umc-link-list': LocalJSX.UmcLinkList & JSXBase.HTMLAttributes<HTMLUmcLinkListElement>;
      'umc-link-list-item': LocalJSX.UmcLinkListItem & JSXBase.HTMLAttributes<HTMLUmcLinkListItemElement>;
      'umc-list': LocalJSX.UmcList & JSXBase.HTMLAttributes<HTMLUmcListElement>;
      'umc-list-header': LocalJSX.UmcListHeader & JSXBase.HTMLAttributes<HTMLUmcListHeaderElement>;
      'umc-list-item': LocalJSX.UmcListItem & JSXBase.HTMLAttributes<HTMLUmcListItemElement>;
      'umc-list-item-header': LocalJSX.UmcListItemHeader & JSXBase.HTMLAttributes<HTMLUmcListItemHeaderElement>;
      'umc-listing-block': LocalJSX.UmcListingBlock & JSXBase.HTMLAttributes<HTMLUmcListingBlockElement>;
      'umc-logo': LocalJSX.UmcLogo & JSXBase.HTMLAttributes<HTMLUmcLogoElement>;
      'umc-menu-section': LocalJSX.UmcMenuSection & JSXBase.HTMLAttributes<HTMLUmcMenuSectionElement>;
      'umc-menu-toggle': LocalJSX.UmcMenuToggle & JSXBase.HTMLAttributes<HTMLUmcMenuToggleElement>;
      'umc-publications-list': LocalJSX.UmcPublicationsList & JSXBase.HTMLAttributes<HTMLUmcPublicationsListElement>;
      'umc-publications-list-item': LocalJSX.UmcPublicationsListItem & JSXBase.HTMLAttributes<HTMLUmcPublicationsListItemElement>;
      'umc-publications-list-item-authors': LocalJSX.UmcPublicationsListItemAuthors & JSXBase.HTMLAttributes<HTMLUmcPublicationsListItemAuthorsElement>;
      'umc-publications-list-item-publication': LocalJSX.UmcPublicationsListItemPublication & JSXBase.HTMLAttributes<HTMLUmcPublicationsListItemPublicationElement>;
      'umc-publications-list-item-title': LocalJSX.UmcPublicationsListItemTitle & JSXBase.HTMLAttributes<HTMLUmcPublicationsListItemTitleElement>;
      'umc-researcher': LocalJSX.UmcResearcher & JSXBase.HTMLAttributes<HTMLUmcResearcherElement>;
      'umc-researcher-image': LocalJSX.UmcResearcherImage & JSXBase.HTMLAttributes<HTMLUmcResearcherImageElement>;
      'umc-researchers': LocalJSX.UmcResearchers & JSXBase.HTMLAttributes<HTMLUmcResearchersElement>;
      'umc-researchers-list': LocalJSX.UmcResearchersList & JSXBase.HTMLAttributes<HTMLUmcResearchersListElement>;
      'umc-rich-text-block': LocalJSX.UmcRichTextBlock & JSXBase.HTMLAttributes<HTMLUmcRichTextBlockElement>;
      'umc-search-input': LocalJSX.UmcSearchInput & JSXBase.HTMLAttributes<HTMLUmcSearchInputElement>;
      'umc-section': LocalJSX.UmcSection & JSXBase.HTMLAttributes<HTMLUmcSectionElement>;
      'umc-section-container': LocalJSX.UmcSectionContainer & JSXBase.HTMLAttributes<HTMLUmcSectionContainerElement>;
      'umc-sidebar': LocalJSX.UmcSidebar & JSXBase.HTMLAttributes<HTMLUmcSidebarElement>;
      'umc-style-section': LocalJSX.UmcStyleSection & JSXBase.HTMLAttributes<HTMLUmcStyleSectionElement>;
      'umc-tab': LocalJSX.UmcTab & JSXBase.HTMLAttributes<HTMLUmcTabElement>;
      'umc-tabs': LocalJSX.UmcTabs & JSXBase.HTMLAttributes<HTMLUmcTabsElement>;
      'umc-tag': LocalJSX.UmcTag & JSXBase.HTMLAttributes<HTMLUmcTagElement>;
      'umc-tag': LocalJSX.UmcTag & JSXBase.HTMLAttributes<HTMLUmcTagElement>;
      'umc-tag-list': LocalJSX.UmcTagList & JSXBase.HTMLAttributes<HTMLUmcTagListElement>;
      'umc-teaser': LocalJSX.UmcTeaser & JSXBase.HTMLAttributes<HTMLUmcTeaserElement>;
      'umc-teaser-body': LocalJSX.UmcTeaserBody & JSXBase.HTMLAttributes<HTMLUmcTeaserBodyElement>;
      'umc-teaser-header': LocalJSX.UmcTeaserHeader & JSXBase.HTMLAttributes<HTMLUmcTeaserHeaderElement>;
      'umc-teaser-image': LocalJSX.UmcTeaserImage & JSXBase.HTMLAttributes<HTMLUmcTeaserImageElement>;
      'umc-teaser-link': LocalJSX.UmcTeaserLink & JSXBase.HTMLAttributes<HTMLUmcTeaserLinkElement>;
      'umc-teaser-section': LocalJSX.UmcTeaserSection & JSXBase.HTMLAttributes<HTMLUmcTeaserSectionElement>;
      'umc-teaser-text': LocalJSX.UmcTeaserText & JSXBase.HTMLAttributes<HTMLUmcTeaserTextElement>;
      'umc-theme': LocalJSX.UmcTheme & JSXBase.HTMLAttributes<HTMLUmcThemeElement>;
      'umc-title-block': LocalJSX.UmcTitleBlock & JSXBase.HTMLAttributes<HTMLUmcTitleBlockElement>;
    }
  }
}


