/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UmcColumn {
    'alignment': string;
    'colspan': string;
  }
  interface UmcColumnSection {}
  interface UmcContentSection {}
  interface UmcDevStatusbar {}
  interface UmcGridBlock {}
  interface UmcGridRow {}
  interface UmcHeader {}
  interface UmcHeaderSection {}
  interface UmcLinkList {
    'orientation': string;
    'title': string;
  }
  interface UmcLinkListItem {
    'active': boolean;
    'href': string;
    'icon': string;
    'label': string;
  }
  interface UmcLogo {
    'src': string;
  }
  interface UmcMenuToggle {
    'icon': string;
    'label': string;
    'reverse': boolean;
  }
  interface UmcSidebar {}
  interface UmcTab {
    'active': boolean;
    'label': string;
  }
  interface UmcTabs {}
}

declare global {


  interface HTMLUmcColumnElement extends Components.UmcColumn, HTMLStencilElement {}
  var HTMLUmcColumnElement: {
    prototype: HTMLUmcColumnElement;
    new (): HTMLUmcColumnElement;
  };

  interface HTMLUmcColumnSectionElement extends Components.UmcColumnSection, HTMLStencilElement {}
  var HTMLUmcColumnSectionElement: {
    prototype: HTMLUmcColumnSectionElement;
    new (): HTMLUmcColumnSectionElement;
  };

  interface HTMLUmcContentSectionElement extends Components.UmcContentSection, HTMLStencilElement {}
  var HTMLUmcContentSectionElement: {
    prototype: HTMLUmcContentSectionElement;
    new (): HTMLUmcContentSectionElement;
  };

  interface HTMLUmcDevStatusbarElement extends Components.UmcDevStatusbar, HTMLStencilElement {}
  var HTMLUmcDevStatusbarElement: {
    prototype: HTMLUmcDevStatusbarElement;
    new (): HTMLUmcDevStatusbarElement;
  };

  interface HTMLUmcGridBlockElement extends Components.UmcGridBlock, HTMLStencilElement {}
  var HTMLUmcGridBlockElement: {
    prototype: HTMLUmcGridBlockElement;
    new (): HTMLUmcGridBlockElement;
  };

  interface HTMLUmcGridRowElement extends Components.UmcGridRow, HTMLStencilElement {}
  var HTMLUmcGridRowElement: {
    prototype: HTMLUmcGridRowElement;
    new (): HTMLUmcGridRowElement;
  };

  interface HTMLUmcHeaderElement extends Components.UmcHeader, HTMLStencilElement {}
  var HTMLUmcHeaderElement: {
    prototype: HTMLUmcHeaderElement;
    new (): HTMLUmcHeaderElement;
  };

  interface HTMLUmcHeaderSectionElement extends Components.UmcHeaderSection, HTMLStencilElement {}
  var HTMLUmcHeaderSectionElement: {
    prototype: HTMLUmcHeaderSectionElement;
    new (): HTMLUmcHeaderSectionElement;
  };

  interface HTMLUmcLinkListElement extends Components.UmcLinkList, HTMLStencilElement {}
  var HTMLUmcLinkListElement: {
    prototype: HTMLUmcLinkListElement;
    new (): HTMLUmcLinkListElement;
  };

  interface HTMLUmcLinkListItemElement extends Components.UmcLinkListItem, HTMLStencilElement {}
  var HTMLUmcLinkListItemElement: {
    prototype: HTMLUmcLinkListItemElement;
    new (): HTMLUmcLinkListItemElement;
  };

  interface HTMLUmcLogoElement extends Components.UmcLogo, HTMLStencilElement {}
  var HTMLUmcLogoElement: {
    prototype: HTMLUmcLogoElement;
    new (): HTMLUmcLogoElement;
  };

  interface HTMLUmcMenuToggleElement extends Components.UmcMenuToggle, HTMLStencilElement {}
  var HTMLUmcMenuToggleElement: {
    prototype: HTMLUmcMenuToggleElement;
    new (): HTMLUmcMenuToggleElement;
  };

  interface HTMLUmcSidebarElement extends Components.UmcSidebar, HTMLStencilElement {}
  var HTMLUmcSidebarElement: {
    prototype: HTMLUmcSidebarElement;
    new (): HTMLUmcSidebarElement;
  };

  interface HTMLUmcTabElement extends Components.UmcTab, HTMLStencilElement {}
  var HTMLUmcTabElement: {
    prototype: HTMLUmcTabElement;
    new (): HTMLUmcTabElement;
  };

  interface HTMLUmcTabsElement extends Components.UmcTabs, HTMLStencilElement {}
  var HTMLUmcTabsElement: {
    prototype: HTMLUmcTabsElement;
    new (): HTMLUmcTabsElement;
  };
  interface HTMLElementTagNameMap {
    'umc-column': HTMLUmcColumnElement;
    'umc-column-section': HTMLUmcColumnSectionElement;
    'umc-content-section': HTMLUmcContentSectionElement;
    'umc-dev-statusbar': HTMLUmcDevStatusbarElement;
    'umc-grid-block': HTMLUmcGridBlockElement;
    'umc-grid-row': HTMLUmcGridRowElement;
    'umc-header': HTMLUmcHeaderElement;
    'umc-header-section': HTMLUmcHeaderSectionElement;
    'umc-link-list': HTMLUmcLinkListElement;
    'umc-link-list-item': HTMLUmcLinkListItemElement;
    'umc-logo': HTMLUmcLogoElement;
    'umc-menu-toggle': HTMLUmcMenuToggleElement;
    'umc-sidebar': HTMLUmcSidebarElement;
    'umc-tab': HTMLUmcTabElement;
    'umc-tabs': HTMLUmcTabsElement;
  }
}

declare namespace LocalJSX {
  interface UmcColumn {
    'alignment'?: string;
    'colspan'?: string;
  }
  interface UmcColumnSection {}
  interface UmcContentSection {}
  interface UmcDevStatusbar {}
  interface UmcGridBlock {}
  interface UmcGridRow {}
  interface UmcHeader {}
  interface UmcHeaderSection {}
  interface UmcLinkList {
    'orientation'?: string;
    'title'?: string;
  }
  interface UmcLinkListItem {
    'active'?: boolean;
    'href'?: string;
    'icon'?: string;
    'label'?: string;
  }
  interface UmcLogo {
    'src'?: string;
  }
  interface UmcMenuToggle {
    'icon'?: string;
    'label'?: string;
    'reverse'?: boolean;
  }
  interface UmcSidebar {}
  interface UmcTab {
    'active'?: boolean;
    'label'?: string;
  }
  interface UmcTabs {}

  interface IntrinsicElements {
    'umc-column': UmcColumn;
    'umc-column-section': UmcColumnSection;
    'umc-content-section': UmcContentSection;
    'umc-dev-statusbar': UmcDevStatusbar;
    'umc-grid-block': UmcGridBlock;
    'umc-grid-row': UmcGridRow;
    'umc-header': UmcHeader;
    'umc-header-section': UmcHeaderSection;
    'umc-link-list': UmcLinkList;
    'umc-link-list-item': UmcLinkListItem;
    'umc-logo': UmcLogo;
    'umc-menu-toggle': UmcMenuToggle;
    'umc-sidebar': UmcSidebar;
    'umc-tab': UmcTab;
    'umc-tabs': UmcTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'umc-column': LocalJSX.UmcColumn & JSXBase.HTMLAttributes<HTMLUmcColumnElement>;
      'umc-column-section': LocalJSX.UmcColumnSection & JSXBase.HTMLAttributes<HTMLUmcColumnSectionElement>;
      'umc-content-section': LocalJSX.UmcContentSection & JSXBase.HTMLAttributes<HTMLUmcContentSectionElement>;
      'umc-dev-statusbar': LocalJSX.UmcDevStatusbar & JSXBase.HTMLAttributes<HTMLUmcDevStatusbarElement>;
      'umc-grid-block': LocalJSX.UmcGridBlock & JSXBase.HTMLAttributes<HTMLUmcGridBlockElement>;
      'umc-grid-row': LocalJSX.UmcGridRow & JSXBase.HTMLAttributes<HTMLUmcGridRowElement>;
      'umc-header': LocalJSX.UmcHeader & JSXBase.HTMLAttributes<HTMLUmcHeaderElement>;
      'umc-header-section': LocalJSX.UmcHeaderSection & JSXBase.HTMLAttributes<HTMLUmcHeaderSectionElement>;
      'umc-link-list': LocalJSX.UmcLinkList & JSXBase.HTMLAttributes<HTMLUmcLinkListElement>;
      'umc-link-list-item': LocalJSX.UmcLinkListItem & JSXBase.HTMLAttributes<HTMLUmcLinkListItemElement>;
      'umc-logo': LocalJSX.UmcLogo & JSXBase.HTMLAttributes<HTMLUmcLogoElement>;
      'umc-menu-toggle': LocalJSX.UmcMenuToggle & JSXBase.HTMLAttributes<HTMLUmcMenuToggleElement>;
      'umc-sidebar': LocalJSX.UmcSidebar & JSXBase.HTMLAttributes<HTMLUmcSidebarElement>;
      'umc-tab': LocalJSX.UmcTab & JSXBase.HTMLAttributes<HTMLUmcTabElement>;
      'umc-tabs': LocalJSX.UmcTabs & JSXBase.HTMLAttributes<HTMLUmcTabsElement>;
    }
  }
}


